version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: vite-service
    ports:
      - "3000:3000"

  storybook:
    build:
      context: .
      dockerfile: Dockerfile
      target: storybook-service
    ports:
      - "6006:6006"
