name: Build and Deploy to Hostinger

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js (Adjust this step based on your project)
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Build Project (Adjust this command)
        run: npm run build

      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          ftp-server: ${{ secrets.HOSTINGER_FTP_SERVER }}
          ftp-username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
          ftp-password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
          local-dir: dist/
